notes: |
  Plaats een label. Gebaseerd op de Bootstrap 'Label' component
status: ready
collated: true
context:
  __title: Default label
  __explanation: Een default label heeft altijd een <code>.label-default</code> op het element <code>span</code> met <code>.label</code> staan.
  label: Default
  modifier: default
variants:
  - name: label-info
    context:
      __title: Info label
      __explanation: Om een informatief label te krijgen moet <code>.label-default</code> vervangen worden door <code>.label-info</code>.
      label: Info
      modifier: info
  - name: label-primary
    context:
      __title: Primary label
      __explanation: Om een primair label te krijgen moet <code>.label-default</code> vervangen worden door <code>.label-primary</code>.
      label: Primary
      modifier: primary
  - name: label-success
    context:
      __title: Success label
      __explanation: Om een 'succes' label te krijgen moet <code>.label-default</code> vervangen worden door <code>.label-success</code>.
      label: Success
      modifier: success
  - name: label-warning
    context:
      __title: Warning label
      __explanation: Om een 'warning' label te krijgen moet <code>.label-default</code> vervangen worden door <code>.label-warning</code>.
      label: Warning
      modifier: warning
  - name: label-danger
    context:
      __title: Danger label
      __explanation: Om een 'error' label te krijgen moet <code>.label-default</code> vervangen worden door <code>.label-danger</code>.
      label: Danger
      modifier: danger
  - name: label-filter
    context:
      __title: Filter label
      __explanation: Om een label met sluitknop te krijgen moet <code>.closable</code> worden toegevoegd op het niveau van <code>.label</code>.
      label: Filter label
      modifier: default closable

