status: ready
collated: true
context:
  items:
    - 1
    - 2
    - 3
    - 4
    - 5
variants:
  - name: ellipsis
    context:
      items:
        - 5
        - ...
        - 11
        - 12
        - 13
        - ...
        - 35
