status: ready
context:
  menu:
    menuItems:
      - label: Home
      - label: Actueel
      - label: Raadplegen
      - label: Checken
        active: true
      - label: Aanvragen
  breadcrumbs:
    crumbs:
      - label: Home
        url: '#'
      - label: Checken
        url: '#'
  searchGroupInput:
    id: button
    modifier: default
    label: Zoeken
    ariaLabel: Zoeken
    placeholder: Zoeken
    iconOnly: true
    type: submit
    buttonRight: true
    icon: fa fa-search
