status: wip
collated: true
context:
  id: searchbar
  label: Zoeken
  searchbarModifiers: dso-searchbar-closed
variants:
  - name: searchbar-opened
    context:
      searchbarModifiers: dso-searchbar-open
