status: ready
context:
  menuItems:
    - label: Home
      active: true
    - label: Actueel
    - label: Kalender
    - label: Zelf aan de slag
    - label: Documenten
    - label: Over ons
      count: 12
    - label: Wetgeving
